name: "Build"
inputs:
  GCP_ENV_SECRET_NAME:
    description: 'Filename of the environments config stored on GCP'
    required: true
  LOCAL_ENV_FILENAME:
    description: 'Local filename of the environments config'
    required: true
  GCP_SA_KEY_SECRET_NAME:
    description: "Filename of the service account key stored on GCP"
    required: true
  PROJECT:
    description: "The target project"
    required: true
  TAG:
    description: "Tagged version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download environment file
      run: |
        mkdir -p src/environments
        gcloud secrets versions access latest \
          --secret="${{ inputs.GCP_ENV_SECRET_NAME }}" \
          > src/environments/environment.ts
        gcloud secrets versions access latest \
          --secret="${{ inputs.GCP_ENV_SECRET_NAME }}" \
          > src/environments/${{ inputs.LOCAL_ENV_FILENAME }}

    - name: Download service account key (DEV)
      run: |
        mkdir -p server/service-keys/uk
        gcloud secrets versions access latest \
          --secret="${{ inputs.GCP_SA_KEY_SECRET_NAME }}" \
          --project="${{ inputs.GCP_PROJECT }}" \
          > server/service-keys/uk/prod-dignity-dev.json

    - name: Create version file
      run: |
        cat <<EOF > src/environments/.env.ts
        export class env {
          static project_version = "${{ inputs.TAG }}-dev"
        }
        EOF
