name: Calculate functions matrix
description: Action created for cloud-functions-api to calculate which functions should be included in the workflow run

outputs:
  module: 
    value: ${{ steps.calculate-matrix.outputs.module }}

runs:
  using: composite
  steps:
    - name: Checkout code (${{ github.ref }})
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Calculate matrix
      id: calculate-matrix
      shell: bash
      run: |
        declare -A MODULES_BY_PATHS=(
          [functions]="main"
          [src/automation/functions]="automation"
          [src/dignity/functions]="dignity"
          [src/elasticsearch/functions]="elasticsearch"
          [src/elasticsearch/local]="elasticsearch-local"
          [src/environment-router/functions]="environment-router"
          [src/notifications/functions]="notifications"
        )

        case '${{ github.event_name }}' in
          push)
            echo "PUSH"
            firstCommit='${{ github.event.before }}'
            ;;
          pull_request)
            echo "PR"
            firstCommit='origin/main'
            ;;
        esac
        
        DIFF=$(git diff --name-only ${firstCommit} HEAD)
        
        ELEMENTS=""
        
        for path in "${!MODULES_BY_PATHS[@]}"
        do
          if [[ $( grep "^$path" <<< $DIFF ) ]]; then
            ELEMENTS+="{\"name\": \"${MODULES_BY_PATHS[$path]}\", \"path\": \"${path}\"},"
          fi
        done
        
        echo "module=[${ELEMENTS::-1}]" >> "$GITHUB_OUTPUT"
