name: Calculate functions matrix
description: Action created for cloud-functions-api to calculate which functions should be included in the workflow run

inputs:
  initial-ref:
    description: Reference to the starting point of diff in git history (tag, commit hash, branch, etc.)
    required: true
  final-ref:
    description: Reference to the final point of diff in git history (tag, commit hash, branch, etc.)
    required: false
    default: HEAD

outputs:
  module: 
    value: ${{ steps.calculate-matrix.outputs.module }}

runs:
  using: composite
  steps:        
    - name: Calculate matrix
      id: calculate-matrix
      shell: bash
      run: |
        declare -A MODULES_BY_PATHS=(
          [functions]="main"
          [src/automation/functions]="automation"
          [src/dignity/functions]="dignity"
          [src/elasticsearch/functions]="elasticsearch"
          [src/elasticsearch/local]="elasticsearch-local"
          [src/environment-router/functions]="environment-router"
          [src/notifications/functions]="notifications"
        )
        
        DIFF=$(git diff --name-only ${{ inputs.initial-ref }} ${{ inputs.final-ref }})
        
        ELEMENTS=" "
        
        for path in "${!MODULES_BY_PATHS[@]}"
        do
          if [[ $( grep "^$path" <<< $DIFF ) ]]; then
            ELEMENTS+="{\"name\": \"${MODULES_BY_PATHS[$path]}\", \"path\": \"${path}\"},"
          fi
        done
        
        echo "module=[${ELEMENTS::-1}]" >> "$GITHUB_OUTPUT"
