name: "Deploy"
inputs:
  GCP_SA_KEY_NAME:
    description: "The name of the stored Service Account key in GCP"
    required: false
  SA_KEY_FULL_PATH:
    description: "The full path locally to store the Service Account key file from GCP"
    required: false
  DEPLOYMENT_CONFIG_FULL_PATH:
    description: "The full path locally of the config yaml for deployment"
    required: true
  PROJECT:
    description: "The target project in GCP"
    required: true
  TAG:
    description: "Tagged version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Convert tag to App Engine version
      id: convert_tag
      shell: bash
      run: |
        TAG="${{ inputs.TAG }}"
        GCP_TAG="${TAG//./-}"
        echo "gcp_tag=$GCP_TAG" >> $GITHUB_OUTPUT

    - name: Download service account key
      shell: bash
      if: ${{ inputs.GCP_SA_KEY_NAME && inputs.SA_KEY_FULL_PATH }}
      run: |
        KEY_PATH="${{ inputs.SA_KEY_FULL_PATH }}"
        KEY_DIR=$(dirname "$KEY_PATH")
        
        mkdir -p "$KEY_DIR"
        
        gcloud secrets versions access latest \
        --secret="${{ inputs.GCP_SA_KEY_NAME }}" \
        --project="${{ inputs.PROJECT }}" \
        > "$KEY_PATH"

    - name: Install server dependencies
      shell: bash
      working-directory: server
      run: npm ci

    - name: Deploy app
      shell: bash
      working-directory: server
      run: |
        gcloud app deploy ${{ inputs.DEPLOYMENT_CONFIG_FULL_PATH }} \
          --no-promote \
          --quiet \
          --project "${{ inputs.PROJECT }}" \
          --version ${{ steps.convert_tag.outputs.gcp_tag }}