name: Version Tag

on:
  workflow_call:

permissions:
  contents: write
  packages: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project-code
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'project-code/.nvmrc'

      - name: Confirm node version
        run: node -v

      - name: Checkout config
        uses: actions/checkout@v4
        with:
          repository: dignityfalconer/.github
          path: config

      - name: Install version tag dependencies
        working-directory: config/version_tag_config
        run: npm ci

      - name: Run semantic-release
        working-directory: config/version_tag_config
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --no-ci --cwd ../../project-code --extends ./release.config.cjs
