name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The target environment for deployment"
        required: true
        type: string
      TAG:
        description: "Tag to checkout"
        required: true
        type: string
      DEPLOYMENT_CONFIG_FILENAME:
        description: "The config filename for deployment"
        required: true
        type: string
      BASE_DIR:
        description: "Optional base directory to run commands in"
        required: false
        type: string
        default: "."
      SECRETS_CONFIG_NAME:
        description: "The name of the stored config file in GCP secrets manager"
        required: false
        type: string
      LOCAL_CONFIG_FULL_PATH:
        description: "The full path locally to store the config file from GCP secrets manager"
        required: false
        type: string
      SECRETS_SA_KEY_NAME:
        description: "The name of the stored Service Account key in GCP secrets manager"
        required: false
        type: string
      LOCAL_SA_KEY_FULL_PATH:
        description: "The full path locally to store the Service Account key file from GCP secrets manager"
        required: false
        type: string
    secrets:
      PROJECT:
        description: "The target project for deployment"
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        description: "The workload identity provider specific for the environment"
        required: true
      SERVICE_ACCOUNT:
        description: "The service account specific for the environment"
        required: true

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Validate tag
        id: validate_tag
        run: |
          TAG="${{ inputs.TAG }}"
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error ::Invalid tag '$TAG'. Expected format: vMAJOR.MINOR.PATCH"
            exit 1
          fi
          echo "Using tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout code (${{ steps.validate_tag.outputs.tag }})
        uses: actions/checkout@v4
#        with:
#          ref: refs/tags/${{ steps.validate_tag.outputs.tag }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ format('{0}/.nvmrc', inputs.BASE_DIR) }}

      - name: Confirm node version
        run: node -v

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Debug GitHub OIDC token
        run: |
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'

      - name: Download config file
        if: ${{ inputs.SECRETS_CONFIG_NAME && inputs.LOCAL_CONFIG_FULL_PATH }}
        run: |
          mkdir -p src/config
          gcloud secrets versions access latest \
            --secret="${{ inputs.SECRETS_CONFIG_NAME }}" \
            > ${{ inputs.LOCAL_CONFIG_FULL_PATH }}

      - name: Download key file
        if: ${{ inputs.SECRETS_SA_KEY_NAME && inputs.LOCAL_SA_KEY_FULL_PATH }}
        run: |
          mkdir -p src/service-keys/uk
          gcloud secrets versions access latest \
            --secret="${{ inputs.SECRETS_SA_KEY_NAME }}" \
            > ${{ inputs.LOCAL_SA_KEY_FULL_PATH }}

      - name: Prepare .npmrc
        working-directory: src
        run: |
          rm -f .npmrc
          echo "@dignityfalconer:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Create version file
        working-directory: src
        run: |
          VERSION="${{ steps.validate_tag.outputs.tag }}-${{ inputs.ENVIRONMENT }}"
          node version --version=$VERSION

      - name: Convert tag to App Engine tag
        id: convert_tag
        run: |
          TAG="${{ steps.validate_tag.outputs.tag }}"
          GCP_TAG="${TAG//./-}"
          echo "Converted GCP_TAG: $GCP_TAG"
          echo "gcp_tag=$GCP_TAG" >> $GITHUB_OUTPUT

      - name: Deploying to ${{ inputs.ENVIRONMENT }} (${{ steps.convert_tag.outputs.gcp_tag }})  # TODO: need to change to --promote \ --stop-previous-version \
        run: |
          gcloud builds submit \
            --project "${{ env.DEV_GCP_PROJECT }}" \
            --config cloudbuild.yaml \
            --substitutions=_VERSION=${{ steps.convert_tag.outputs.gcp_tag }},_APP_YAML=${{ inputs.DEPLOYMENT_CONFIG_FILENAME }} \
            --region=europe-west2 \
            src
