name: Version Tag

on:
  workflow_call:

permissions:
  contents: write
  packages: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Confirm node version
        run: node -v

      - name: Install shared version tag dependencies
        working-directory: ${{ github.action_path }}/shared_version_tag_config
        run: npm ci

      - name: Run semantic-release
        working-directory: ${{ github.action_path }}/shared_version_tag_config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
